### ISSUE TITLE
code inversion as -1, 1 or TRUE FALSE

### ISSUE THREAD

**Issue by maxheld83** [joaordaniel/qsort#5]
if I understand correctly, the inversion columns are stored as `0` and `1` numerics, which I find a little confusing.

```
pederson_s_inv: num [1:90] 0 0 0 0 0 0 0 0 1 0 ...
```

Shouldn't it be proper logical values *or* -1,1, so that the multiplication works?

as per https://github.com/openjournals/joss-reviews/issues/911

**Comment by joaordaniel** [comment]
Inversion columns can be specified in different ways and inverting item scores in scales does not equal to multiplying the score by -1. Inverted/reversed item scores correspond to subtracting item scores from max + 1, so that all scores have the same direction.
